### ISSUE TITLE
Feature idea: Slack Log Filter

### ISSUE THREAD

**Issue by browniebroke** [junhwi/python-slack-logger#1]
Hi! Cool library, found it while thinking about starting something similar!

I want to suggest the addition of a `SlackLogFilter` that would let one do something like:
```python
logger.info(':tada: Something awesome happened', extra={'notify_slack': True})
```

We use logging for all sort of things in a Django app, and we only want a very small amount of things to notify us in Slack, it's doable using the `extra` keyword argument, we can later filter them.

Opening this to see whether you'd be open to such a change? If so I'm happy to send a pull request.

**Comment by junhwi** [comment]
@browniebroke
Hi! Thanks for good suggestion. :+1:
I'm happy to such a change. Please send a pull request freely.
